### ISSUE TITLE
React Country Flag is not showing emoji on windows OS

### ISSUE THREAD

**Issue by Kamran95** [danalloway/react-country-flag#56]
We have developed our product on Linux on which this library was working just fine
but on moving to windows emoji is not displaying on all browsers except Firefox
Kindly resolve this issue as this has a great impact on our system
On browsers except for firefox, it displays us for the united states in small alphabets rather than the united states flag

**Comment by hero9991** [comment]
The same issue

**Comment by danalloway** [comment]
@Kamran95 @hero9991 

Hi all, my understanding is that Windows does not support country flag emojis.
`emojiSupport` will always returns true because Windows does support emoji's just not country flags, due to political reasons.

This library relies on native emojji support as well as third-party flag SVG's and does not handle or control the assets at all, as it's just a simple React component.

My suggestion is to use SVG's if you have to support Windows.
